// <auto-generated />
using System;
using Led.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Led.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329071244_Device_Name_Rename")]
    partial class Device_Name_Rename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("led")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Led.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IpAddress")
                        .IsUnique();

                    b.ToTable("device", "led");
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("Invert")
                        .HasColumnType("boolean")
                        .HasColumnName("invert");

                    b.Property<int>("LedStripTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("led_strip_type_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LedStripTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("led_strip", "led");
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStripType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("led_strip_type", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EffectTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_type_id");

                    b.Property<Guid>("LedStripId")
                        .HasColumnType("uuid")
                        .HasColumnName("led_strip_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<int>("ParameterJsonSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("parameter_json_schema_version");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.HasKey("Id");

                    b.HasIndex("EffectTypeId");

                    b.HasIndex("LedStripId");

                    b.HasIndex("SceneId", "LedStripId")
                        .IsUnique();

                    b.ToTable("effect", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.EffectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsBuiltin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_builtin");

                    b.Property<bool>("IsImplemented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_implmeneted");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("effect_type", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("scene", "led");
                });

            modelBuilder.Entity("Led.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.HasKey("Id");

                    b.ToTable("tenant", "led");
                });

            modelBuilder.Entity("Led.Domain.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("tenant_user", "led");
                });

            modelBuilder.Entity("Led.Domain.Tenants.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("users", "led");
                });

            modelBuilder.Entity("Led.Domain.Devices.Device", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.HasKey("DeviceId");

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.DeviceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("DeviceId");

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.SerialNumber", "SerialNumber", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("serial_number");

                            b1.HasKey("DeviceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("SerialNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStrip", b =>
                {
                    b.HasOne("Led.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.LedStrips.LedStripType", null)
                        .WithMany()
                        .HasForeignKey("LedStripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "Brightness", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("brightness");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "DmaChannel", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("dma_channel");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<int>", "Frequency", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("frequency");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("PosNum", "GpioPin", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("gpio_pin");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "LedCount", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("led_count");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<int>", "MaxCurrentMa", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("max_current_ma");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "Voltage", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("voltage");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.LedStrips.ValueObjects.LedStripName", "Name", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.Navigation("Brightness")
                        .IsRequired();

                    b.Navigation("DmaChannel")
                        .IsRequired();

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("GpioPin")
                        .IsRequired();

                    b.Navigation("LedCount")
                        .IsRequired();

                    b.Navigation("MaxCurrentMa")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Voltage")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStripType", b =>
                {
                    b.OwnsOne("Led.Domain.LedStrips.ValueObjects.LedStripTypeName", "TypeName", b1 =>
                        {
                            b1.Property<int>("LedStripTypeId")
                                .HasColumnType("integer");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("name");

                            b1.HasKey("LedStripTypeId");

                            b1.ToTable("led_strip_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripTypeId");
                        });

                    b.Navigation("TypeName")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.Effect", b =>
                {
                    b.HasOne("Led.Domain.Scenes.EffectType", null)
                        .WithMany()
                        .HasForeignKey("EffectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Led.Domain.LedStrips.LedStrip", null)
                        .WithMany()
                        .HasForeignKey("LedStripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Scenes.Scene", null)
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.EffectParameter", "ParameterJson", b1 =>
                        {
                            b1.Property<Guid>("EffectId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1280);

                            b1.HasKey("EffectId");

                            b1.ToTable("effect", "led");

                            b1
                                .ToJson("parameter_json")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EffectId");
                        });

                    b.Navigation("ParameterJson")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.EffectType", b =>
                {
                    b.OwnsOne("PosNum", "SchemaVersion", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("schema_version");

                            b1.HasKey("EffectTypeId");

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.EffectTypeDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("EffectTypeId");

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.EffectTypeName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("name");

                            b1.HasKey("EffectTypeId");

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("SchemaVersion")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.Scene", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.SceneDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("SceneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("SceneId");

                            b1.ToTable("scene", "led");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.SceneName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SceneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("name");

                            b1.HasKey("SceneId");

                            b1.ToTable("scene", "led");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.Tenant", b =>
                {
                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenant", "led");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.TenantUser", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.User", b =>
                {
                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("username");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
