// <auto-generated />
using System;
using System.Net;
using Led.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Led.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401042019_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("led")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Led.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("device", "led");
                });

            modelBuilder.Entity("Led.Domain.EffectTypes.EffectParameterSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DataTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("parameter_data_type_id");

                    b.Property<Guid>("EffectTypeId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("effect_type_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("EffectTypeId");

                    b.ToTable("effect_parameter_schema", "led");
                });

            modelBuilder.Entity("Led.Domain.EffectTypes.EffectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsBuiltin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_builtin");

                    b.Property<bool>("IsImplemented")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_implmeneted");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid?>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.ToTable("effect_type", "led");
                });

            modelBuilder.Entity("Led.Domain.EffectTypes.ParameterDataType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("parameter_data_type", "led");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Description = "Property represents a true or false value",
                            Name = "True/ False"
                        },
                        new
                        {
                            Id = (short)2,
                            Description = "Property represents a whole number. Ex., 1, 2, 3, ...",
                            Name = "Whole Number"
                        },
                        new
                        {
                            Id = (short)3,
                            Description = "Property represents a whole or floating point number. Ex., 1, 2, 2.5, 3.8, ...",
                            Name = "Rational Number"
                        },
                        new
                        {
                            Id = (short)4,
                            Description = "Property represents a collection of alpha-numeric characters. Ex., \"abc\", \"123abc\", ...",
                            Name = "Collection"
                        });
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("Invert")
                        .HasColumnType("boolean")
                        .HasColumnName("invert");

                    b.Property<short>("LedStripTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("led_strip_type_id");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LedStripTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("led_strip", "led");
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStripType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("led_strip_type", "led");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "SK6812 RGBW"
                        });
                });

            modelBuilder.Entity("Led.Domain.Scenes.ActiveState", b =>
                {
                    b.Property<Guid>("LedStripId")
                        .HasColumnType("uuid")
                        .HasColumnName("led_strip_id");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("LedStripId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SceneId");

                    b.HasIndex("TenantId");

                    b.ToTable("active_state", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EffectTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_type_id");

                    b.Property<Guid>("LedStripId")
                        .HasColumnType("uuid")
                        .HasColumnName("led_strip_id");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<int>("ParameterJsonSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("parameter_json_schema_version");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.HasKey("Id");

                    b.HasIndex("EffectTypeId");

                    b.HasIndex("LedStripId");

                    b.HasIndex("SceneId", "LedStripId")
                        .IsUnique();

                    b.ToTable("effect", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.LedState", b =>
                {
                    b.Property<Guid>("EffectId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_id");

                    b.Property<short>("LedIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("led_index");

                    b.Property<short>("Blue")
                        .HasColumnType("smallint")
                        .HasColumnName("blue");

                    b.Property<short>("Green")
                        .HasColumnType("smallint")
                        .HasColumnName("green");

                    b.Property<short>("Red")
                        .HasColumnType("smallint")
                        .HasColumnName("red");

                    b.Property<short>("White")
                        .HasColumnType("smallint")
                        .HasColumnName("white");

                    b.HasKey("EffectId", "LedIndex");

                    b.ToTable("led_state", "led");
                });

            modelBuilder.Entity("Led.Domain.Scenes.Scene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("scene", "led");
                });

            modelBuilder.Entity("Led.Domain.Schedules.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_enabled");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<DateTime?>("RunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at_utc");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uuid")
                        .HasColumnName("scene_id");

                    b.Property<short>("ScheduleTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("schedule_type_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("ScheduleTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("schedule", "led");
                });

            modelBuilder.Entity("Led.Domain.Schedules.ScheduleType", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("schedule_type", "led");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "One Off"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Recurring"
                        });
                });

            modelBuilder.Entity("Led.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.HasKey("Id");

                    b.ToTable("tenant", "led");
                });

            modelBuilder.Entity("Led.Domain.Tenants.TenantUser", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("tenant_user", "led");
                });

            modelBuilder.Entity("Led.Domain.Tenants.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.ToTable("users", "led");
                });

            modelBuilder.Entity("Led.Domain.Devices.Device", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("DeviceId");

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.DeviceIpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<IPAddress>("Value")
                                .IsRequired()
                                .HasColumnType("inet")
                                .HasColumnName("ip_address");

                            b1.HasKey("DeviceId");

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.DeviceName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.HasKey("DeviceId");

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("Led.Domain.Devices.ValueObjects.SerialNumber", "SerialNumber", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("serial_number");

                            b1.HasKey("DeviceId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("device", "led");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("IpAddress")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("SerialNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.EffectTypes.EffectParameterSchema", b =>
                {
                    b.HasOne("Led.Domain.EffectTypes.ParameterDataType", null)
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.EffectTypes.EffectType", null)
                        .WithMany()
                        .HasForeignKey("EffectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.EffectTypes.ValueObjects.ParameterDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("EffectParameterSchemaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("EffectParameterSchemaId");

                            b1.ToTable("effect_parameter_schema", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectParameterSchemaId");
                        });

                    b.OwnsOne("Led.Domain.EffectTypes.ValueObjects.ParameterKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("EffectParameterSchemaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EffectTypeId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("effect_type_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("key");

                            b1.HasKey("EffectParameterSchemaId");

                            b1.HasIndex("EffectTypeId", "Value")
                                .IsUnique();

                            b1.ToTable("effect_parameter_schema", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectParameterSchemaId");
                        });

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.ParameterAllowedValues", "AllowedValues", b1 =>
                        {
                            b1.Property<Guid>("EffectParameterSchemaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(1280)
                                .HasColumnType("character varying(1280)")
                                .HasColumnName("allowed_values");

                            b1.HasKey("EffectParameterSchemaId");

                            b1.ToTable("effect_parameter_schema", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectParameterSchemaId");
                        });

                    b.Navigation("AllowedValues")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Key")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.EffectTypes.EffectType", b =>
                {
                    b.OwnsOne("PosNum", "SchemaVersion", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("schema_version");

                            b1.HasKey("EffectTypeId");

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.OwnsOne("Led.Domain.EffectTypes.ValueObjects.EffectTypeDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("EffectTypeId");

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.OwnsOne("Led.Domain.EffectTypes.ValueObjects.EffectTypeName", "Name", b1 =>
                        {
                            b1.Property<Guid>("EffectTypeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("name");

                            b1.HasKey("EffectTypeId");

                            b1.HasIndex("Value")
                                .HasFilter("tenant_id IS NULL");

                            b1.HasIndex("TenantId", "Value")
                                .IsUnique();

                            b1.ToTable("effect_type", "led");

                            b1.WithOwner()
                                .HasForeignKey("EffectTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("SchemaVersion")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.LedStrips.LedStrip", b =>
                {
                    b.HasOne("Led.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.LedStrips.LedStripType", null)
                        .WithMany()
                        .HasForeignKey("LedStripTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "Brightness", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("brightness");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "DmaChannel", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DeviceId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("device_id");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("dma_channel");

                            b1.HasKey("LedStripId");

                            b1.HasIndex("DeviceId", "Value")
                                .IsUnique();

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<int>", "Frequency", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("frequency");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("PosNum", "GpioPin", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DeviceId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("device_id");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("gpio_pin");

                            b1.HasKey("LedStripId");

                            b1.HasIndex("DeviceId", "Value")
                                .IsUnique();

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "LedCount", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("led_count");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<int>", "MaxCurrentMa", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("max_current_ma");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.Shared.ValueObjects.PosNum<short>", "Voltage", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<short>("Value")
                                .HasColumnType("smallint")
                                .HasColumnName("voltage");

                            b1.HasKey("LedStripId");

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.OwnsOne("Led.Domain.LedStrips.ValueObjects.LedStripName", "Name", b1 =>
                        {
                            b1.Property<Guid>("LedStripId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("LedStripId");

                            b1.HasIndex("TenantId", "Value")
                                .IsUnique();

                            b1.ToTable("led_strip", "led");

                            b1.WithOwner()
                                .HasForeignKey("LedStripId");
                        });

                    b.Navigation("Brightness")
                        .IsRequired();

                    b.Navigation("DmaChannel")
                        .IsRequired();

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("GpioPin")
                        .IsRequired();

                    b.Navigation("LedCount")
                        .IsRequired();

                    b.Navigation("MaxCurrentMa")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Voltage")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.ActiveState", b =>
                {
                    b.HasOne("Led.Domain.Devices.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.LedStrips.LedStrip", null)
                        .WithOne()
                        .HasForeignKey("Led.Domain.Scenes.ActiveState", "LedStripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Scenes.Scene", null)
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.ActiveStateSource", "Source", b1 =>
                        {
                            b1.Property<Guid>("ActiveStateLedStripId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("source");

                            b1.HasKey("ActiveStateLedStripId");

                            b1.ToTable("active_state", "led");

                            b1.WithOwner()
                                .HasForeignKey("ActiveStateLedStripId");
                        });

                    b.Navigation("Source")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.Effect", b =>
                {
                    b.HasOne("Led.Domain.EffectTypes.EffectType", null)
                        .WithMany()
                        .HasForeignKey("EffectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Led.Domain.LedStrips.LedStrip", null)
                        .WithMany()
                        .HasForeignKey("LedStripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Scenes.Scene", null)
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.EffectParameter", "ParameterJson", b1 =>
                        {
                            b1.Property<Guid>("EffectId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1280);

                            b1.HasKey("EffectId");

                            b1.ToTable("effect", "led");

                            b1
                                .ToJson("parameter_json")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EffectId");
                        });

                    b.Navigation("ParameterJson")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.LedState", b =>
                {
                    b.HasOne("Led.Domain.Scenes.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Scenes.Scene", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.SceneDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("SceneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.HasKey("SceneId");

                            b1.ToTable("scene", "led");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.OwnsOne("Led.Domain.Scenes.ValueObjects.SceneName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SceneId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TenantId")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("name");

                            b1.HasKey("SceneId");

                            b1.HasIndex("TenantId", "Value")
                                .IsUnique();

                            b1.ToTable("scene", "led");

                            b1.WithOwner()
                                .HasForeignKey("SceneId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Schedules.Schedule", b =>
                {
                    b.HasOne("Led.Domain.Scenes.Scene", null)
                        .WithMany()
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Schedules.ScheduleType", null)
                        .WithMany()
                        .HasForeignKey("ScheduleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Led.Domain.Schedules.ValueObjects.CronExpression", "CronExpression", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("cron_expression");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("schedule", "led");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.OwnsOne("Led.Domain.Schedules.ValueObjects.ScheduleLabel", "Label", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("label");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("schedule", "led");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("CronExpression")
                        .IsRequired();

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.Tenant", b =>
                {
                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenant", "led");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.TenantUser", b =>
                {
                    b.HasOne("Led.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Led.Domain.Tenants.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Led.Domain.Tenants.User", b =>
                {
                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "FirstName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Name", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Led.Domain.Tenants.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("username");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "led");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
